# fly.toml app configuration file generated for meilisearch-divine-waterfall-7994 on 2025-12-13T17:07:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meilisearch-divine-waterfall-7994'
primary_region = 'gru'

[http_service]
  internal_port = 7700
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "meilisearch"
  destination = "/meili_data"
  snapshot_retention = 2